calibrated: 1
equilibrium:
    sign: -1
    signFlexor: -1
    signExtensor: -1
    nameFlexor: "shoulder_adductor"
    nameExtensor: "shoulder_abductor"
    servoRange: 6.2832
    servoOffset: 0
signEncoder: 1
signJoint: 1
name: "shoulder_pitch"
nameEncoder: "shoulder_pitch_encoder"
minAngle: -1.1
maxAngle: 1.1
maxAbsForwardError: 0.25
gains:
    P: 0.065
    I: 0.00001
    D: 0.025
